AlphaForums/Controllers/PostController.cs
using AlphaForums.Data;
using AlphaForums.Data.Models;
using AlphaForums.Models.PostViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace AlphaForums.Controllers;

public class PostController : Controller
{
    private readonly IPost _postService;
    private readonly IForum _forumService;
    private readonly IApplicationUser _userService;
    private readonly UserManager<ApplicationUser> _userManager;

    public PostController(IPost postService, IForum forumService, UserManager<ApplicationUser> userManager,
        IApplicationUser userService)
    {
        _postService = postService;
        _forumService = forumService;
        _userManager = userManager;
        _userService = userService;
    }

    [HttpGet]
    public IActionResult Index(int id, int? page, int? pageSize)
    {
        page ??= 1;
        pageSize ??= 5;
        var post = _postService.GetById(id);
        var replies = BuildPostReplies(post.Relies);
        var model = new PostIndexModel
        {
            Id = post.Id,
            Title = post.Title,
            AuthorId = post.User.Id,
            AuthorName = post.User.UserName,
            AuthorImageUrl = post.User.ProfileImageUrl,
            AuthorRating = post.User.Rating,
            Created = post.Created,
            PostContent = post.Content,
            Replies = replies.ToPagedList((int)page, (int)pageSize),
            ForumId = post.Forum.Id,
            ForumName = post.Forum.Title,
            IsAuthor = IsAuthor(post.User)
        };
        return View(model);
    }


    [HttpGet]
    [Authorize]
    public IActionResult Create(int id)
    {
        var forum = _forumService.GetById(id);
        var model = new NewPostModel
        {
            ForumName = forum.Title,
            ForumId = forum.Id,
            ForumImageUrl = forum.ImageUrl,
            AuthorName = User.Identity?.Name ?? "Unknown",
        };
        return View(model);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> AddPost(NewPostModel model)
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null) return View("Error");
        var post = BuildPost(model, user);
        await _postService.Add(post);
        await _userService.UpdateUserRating(user.Id, typeof(Post));
        return RedirectToAction("Index", "Post", new { post.Id });
    }

    private bool IsAuthor(ApplicationUser postUser)
    {
        return  _userManager.GetUserId(User) == postUser.Id;
    }

    private IEnumerable<PostRelyModel> BuildPostReplies(IEnumerable<PostReply> replies)
    {
        return replies.Select(r => new PostRelyModel
        {
            Id = r.Id,
            AuthorName = r.User.UserName,
            AuthorId = r.User.Id,
            AuthorImageUrl = r.User.ProfileImageUrl,
            AuthorRating = r.User.Rating,
            Created = r.Created,
            ReplyContent = r.Content,
            IsAuthor = IsAuthor(r.User)
        });
    }

    private Post BuildPost(NewPostModel model, ApplicationUser user)
    {
        var forum = _forumService.GetById(model.ForumId);
        return new Post
        {
            Title = model.Title,
            Content = model.Content,
            Created = DateTime.Now,
            User = user,
            Forum = forum
        };
    }
    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
        var post = _postService.GetById(id);
        if (post == null) return View("Error");
        await _postService.Delete(id);
        return RedirectToAction("Topic", "Forum", new { id = post.Forum.Id });
    }
    [Authorize]
    public IActionResult Edit(int id)
    {
        var post = _postService.GetById(id);
        if (post == null) return View("Error");
        var model = new UpdatePostModel
        {
            PostId = post.Id,
            ForumName = post.Forum.Title,
            ForumId = post.Forum.Id,
            ForumImageUrl = post.Forum.ImageUrl,
            AuthorName = User.Identity?.Name ?? "Unknown",
            Title = post.Title,
            Content = post.Content
        };
        return View(model);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> EditPost(UpdatePostModel model)
    {
        await _postService.EditPost(model.PostId, model.Title, model.Content);
        return RedirectToAction("Index", "Post", new { id = model.PostId });
    }
}

AlphaForums/Controllers/ReplyController.cs
using AlphaForums.Data;
using AlphaForums.Data.Models;
using AlphaForums.Models.PostViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AlphaForums.Controllers;

[Authorize]
public class ReplyController : Controller
{
    private readonly IPost _postService;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IApplicationUser _userService;


    public ReplyController(IPost postService, UserManager<ApplicationUser> userManager, IApplicationUser userService)
    {
        _postService = postService;
        _userManager = userManager;
        _userService = userService;
    }

    public async Task<IActionResult> Create(int id)
    {
        var post = _postService.GetById(id);
        if (User.Identity == null) return View("Error");
        var user = await _userManager.FindByNameAsync(User.Identity.Name??"");
        if(user == null)  return View("Error");
        var model = new PostRelyModel
        {
            PostContent = post.Content,
            PostTitle = post.Title,
            PostId = post.Id,
            AuthorId = user.Id,
            AuthorName = User.Identity.Name,
            AuthorImageUrl = user.ProfileImageUrl,
            AuthorRating = user.Rating,
            IsAuthor = User.IsInRole("Admin"),
            
            ForumName = post.Forum.Title,
            ForumId = post.Forum.Id,
            ForumImageUrl = post.Forum.ImageUrl,
            Created = DateTime.Now
            
        };
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> AddReply(PostRelyModel model)
    {
        var userId = _userManager.GetUserId(User);
        if(userId == null) return View("Error");
        var user = await _userManager.FindByIdAsync(userId);
        var reply = BuildReply(model, user);
        await _postService.AddReply(reply);
        await _userService.UpdateUserRating(userId, typeof(PostReply));
        return RedirectToAction("Index", "Post", new { id = model.PostId });
    }

    private PostReply BuildReply(PostRelyModel model, ApplicationUser user)
    {
        var post = _postService.GetById(model.PostId);
        return new PostReply
        {
            Post = post,
            Content = model.ReplyContent,
            Created = DateTime.Now,
            User = user
        };
    }
}

AlphaForums/Views/Post/Create.cshtml
@model AlphaForums.Models.PostViewModels.NewPostModel
<div class="container body-content">
    <div class="row sectionHeader">
        <div class="sectionHeading text-bold">
            New Post | @Model.ForumName
        </div>
        <div class="flex mb-2 p-0">
            <div class="forumLogo"
                 style="background-image: url(@Model.ForumImageUrl)">
            </div>
            <span id="headingBtn">
                <a asp-controller="Forum" asp-action="Topic"
                   asp-route-id="@Model.ForumId" class="btn btn-back">
                    Back to Forum
                </a>
            </span>
        </div>

    </div>
    <div class="row">
        <form asp-controller="Post" asp-action="AddPost" method="POST" id="addPostForm">
            <div class="form-control rounded-0 border-0">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control rounded-0"/>
            </div>

            <div class="form-control rounded-0 border-0">
                <label asp-for="Content"></label>
                <textarea rows="20" asp-for="Content" class="form-control rounded-0"></textarea>
            </div>

            <input asp-for="ForumId" type="hidden"/>

            <button type="submit" id="submitPostBtn" class="btn btn-submitPost">Submit Post</button>
        </form>
    </div>

</div>

AlphaForums/Views/Post/Edit.cshtml
@model AlphaForums.Models.PostViewModels.UpdatePostModel
<div class="container body-content">
    <div class="row sectionHeader">
        <div class="sectionHeading text-bold">
            Edit Post | @Model.ForumName
        </div>
        <div class="flex mb-2 p-0">
            <div class="forumLogo"
                 style="background-image: url(@Model.ForumImageUrl)">
            </div>
            <span id="headingBtn">
                <a asp-controller="Forum" asp-action="Topic"
                   asp-route-id="@Model.ForumId" class="btn btn-back">
                    Back to Forum
                </a>
            </span>
        </div>

    </div>
    <div class="row">
        <form asp-controller="Post" asp-action="EditPost" method="POST" id="addPostForm">
            <div class="form-control rounded-0 border-0">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control rounded-0" value="@Model.Title"/>
            </div>

            <div class="form-control rounded-0 border-0">
                <label asp-for="Content"></label>
                <textarea rows="20" asp-for="Content" class="form-control rounded-0" value="@Model.Content"></textarea>
            </div>
            
            <input asp-for="PostId" type="hidden"/>
            <input asp-for="ForumId" type="hidden"/>
            
            <button type="submit" id="submitPostBtn" class="btn btn-submitPost">Save Post</button>
        </form>
    </div>

</div>

AlphaForums/Views/Post/Index.cshtml
@using X.PagedList.Mvc.Core
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model AlphaForums.Models.PostViewModels.PostIndexModel

<div class="container body-content">
    <div class="row postHeader">
        <div class="postHeading">
            <span class="postIndexTitle text-bold">
                @Model.Title
            </span>

            <span id="headingBtn" class="ms-2">
                <a asp-controller="Forum" asp-action="Topic" asp-route-id="@Model.ForumId" class="btn btn-back">
                    Back to @Model.ForumName
                </a>
            </span>

            @if (@Model.IsAuthor)
            {
                <span class="f-right ms-2">
                    <a class="btn btn-delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">
                        Delete
                    </a>
                    <div class="modal fade text-dark" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5 text-bold" id="confirmDeleteLabel">Confirm delete</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Do you want delete this post?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a asp-controller="Post" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </span>
                <span class="f-right">
                    <a asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-edit ">
                        Edit
                    </a>
                </span>
            }
        </div>
    </div>


    <div class="row" id="postIndexContent">
        <div class="col-md-3 postAuthorContainer">
            <div class="postAuthorImage" style="background-image: url('@Model.AuthorImageUrl')"></div>
            <a asp-controller="Profile" asp-action="Detail" asp-route-id="@Model.AuthorId" class="authorName">
                @Model.AuthorName
            </a>
            <span class="postData">@Model.Created</span>


        </div>
        <div class="col-md-9 postContentContainer">
            <div class="postContent">
                @Html.Raw((Model.PostContent))
            </div>
        </div>
    </div>

    <div class="row mb-3" id="replyDivider"></div>
    @if (User.Identity?.IsAuthenticated == true)
    {
        <div class="row">
            <span class="replyBar">
                <a asp-controller="Reply" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-newReply">
                    Post Reply
                </a>
            </span>

        </div>
    }

    @if (Model.Replies.Any())
    {
        @foreach (var reply in Model.Replies)
        {
            <div class="row replyContent">
                <div class="col-md-3 replyAuthorContainer">
                    <div class="postAuthorImage" style="background-image: url(@reply.AuthorImageUrl)"></div>
                    <a asp-controller="Profile" asp-action="Detail" asp-route-id="@reply.AuthorId" class="authorName">
                        @reply.AuthorName
                    </a>

                    <span class="postData">@reply.Created</span>
                </div>
                <div class="col-md-9 replyContentContainer">
                    <div class="postContent">
                        @Html.Raw(reply.ReplyContent)
                    </div>
                </div>
            </div>
            
        }
        <div class="row">
            <div class="p-0 mt-2">
                @Html.PagedListPager(Model.Replies, page =>
                        Url.Action("Index", new { Model.Id, page, pageSize = ViewBag.pageSize }),
                    new PagedListRenderOptions
                    {
                        LiElementClasses = new string[] { "page-item" },
                        PageClasses = new string[] { "page-link" }
                    }
                )
            </div>

        </div>
    }
    else
    {
        <div class="noPosts">
            <h5>There are no replies to this.<br/></h5>
        </div>
    }
</div>